---

:development: &defaults
  :adapter: sqlite3
  :database: ../../data/wistle/dev.db

:test:
  <<: *defaults
  :database: ":memory:"

:production:
  <<: *defaults
  :database: /u/data/fs/wistle/pro.db

:rake:
  <<: *defaults
