---

development: &defaults
  adapter: sqlite
  path: ../../data/wistle/dev.db

test:
  <<: *defaults
  path: ":memory:"

production:
  <<: *defaults
  path: /u/apps/wistle/shared/data/pro.db

rake:
  <<: *defaults
